# Generated by Django 3.2.12 on 2022-03-11 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220311_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 15, 21, 349254, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 15, 21, 349355, tzinfo=utc)),
        ),
    ]
