# Generated by Django 3.2.12 on 2022-03-11 14:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220311_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalarea',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 15, 57, 86908, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 11, 14, 15, 57, 87012, tzinfo=utc)),
        ),
    ]
